[project]
name = "ragdoll"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tomoya Sawada", email = "stomoya0110@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "datasets>=5.0.1",
    "numpy>=2.4.6",
    "openai>=3.14.0",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

# ------------------------- Ruff -------------------------

[tool.ruff]
fix = true
line-length = 120
indent-width = 4
output-format = "concise"

# Adjust per project.
target-version = "py311"
src = ["src", "tests"]
extend-exclude = ["*.md"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "F405"]
"tests/**/*.py" = [
  "D",
  "ANN201",  # return type is almost always None for test functions.
]

[tool.ruff.lint]
select = [
    # "FAST",  # FastAPI apps.
    "YTT",    # flake8 sys.version usage
    "ANN",    # flake8 function annotations
    "ASYNC",  # flake8 async
    "FBT",    # flake8 boolean trap
    "B",      # flake8 bugbear
    "A",      # flake8 builtins
    "COM",    # flake8 commas
    "C4",     # flake8 comprehensions
    "DTZ",    # flake8 datetimez
    "T10",    # flake8 debugger
    "T20",    # flake8 print
    "EM",     # flake8 error message
    "FA",     # flake8 future annotations
    "ISC",    # flake8 implicit str concat
    "LOG",    # flake8 logging
    "G",      # flake8 logging format
    "PIE",    # flake8 pie
    "PYI",    # flake8 pyi
    "PT",     # flake8 pytest
    "RSE",    # flake8 raise
    "RET",    # flake8 return
    "SIM",    # flake8 simplify
    "SLOT",   # flake8 slots
    "TID252", # flake8 tidy imports -- relative imports from parent module
    # "TID254", # flake8 tidy imports -- lazy import
    # "TID255", # flake8 tidy imports -- lazy import resolved immediately
    "TC",     # flake8 type checking
    "ARG",    # flake8 unused arguments
    "PTH",    # flake8 use pathlib
    "FLY",    # flynt
    "I",      # isort
    "C90",    # McCabe complex structure
    "NPY",    # numpy
    "N",      # pep8 -- naming
    "PERF",   # Perlint
    "E",      # pycodestyle -- error
    "W",      # pycodestyle -- warning
    # "DOC",    # pydoclint
    "D",      # pydocstyle
    "F",      # pyflakes
    "PGH003", # pygrep-hooks -- blanket type ignore
    "PGH004", # pygrep-hooks -- blanket noqa
    "PL",     # pylint
    "UP",     # pyupgrade
    "FURB",   # refurb
    "RUF",    # ruff
    "TRY",    # tryceratops
]
ignore = [
    "SIM108",  # if: a = ...; else: a = ... -> a = ... if else ...
    "PYI021",  # docstring in .pyi.
    "NPY002",  # use np.random.Generator. Most programs still rely on np.random.seed().
    "D105",    # undocumented magic method
    "D107",    # undocumented public __init__
    "D205",    # missing blank line after summary -- ignored to support multiline summary.
    "PLC2701", # import private name -- patching stuff in third party packages requires this. I do this relatively frequently.
    "PLR0913", # too many arguments -- Setting max value isn't solving anything. Just remove this.
    "C408",    # dict().
    "COM812",
]
# flake8-annotations = { allow-star-arg-any = true }  # TODO: decide if we need this.
mccabe = { max-complexity = 14 }  # Taken from pydantic. We'll see if this fits me.
pydocstyle = { convention = 'google' }
future-annotations = true
allowed-confusables = [
    "（",
    "）",
    "：",
    "，",
    "．",
] # frequently used in Japanese comments and docstrings.

fixable = ["ALL"]

# ------------------------- ty -------------------------

[tool.ty.src]
include = ["src", "tests"]

[tool.ty.terminal]
output-format = "concise"

# ------------------------- pytest -------------------------

[tool.pytest]
testpaths = ["tests"]
addopts = [
    "-vv",
    "-s",
    "-ra",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=xml:.reports/coverage.xml",
    "--junitxml=.reports/pytest.xml",
]

[tool.coverage.run]
source = ["src"]
omit = []

[tool.coverage.report]
exclude_also = [
    "@(abc\\.)?abstractmethod",
    'raise\sNotImplementedError',
    '@(typing\.)?overload',
    'class .*\bProtocol\):',
    '(typing\.)?.assert_never',
]
